const String appUserCollections = "AppUsers";
const String workersCollections = "workers";
const String industriesCollections = "Industries";
const String jobPostsCollections = "JobPosts"; //"""JobPosts";
const String companyCollections = "Companies";
const String appVersionsCollection = "AppVersions";
const String transactionsCollection = "Transactions";
const String transactionsByUIDCollection = "TransactionsByUID";
const String appleCollection = "AppleSubscriptionsPaymentDetails";
const String googleCollection = "GoogleSubscriptionsPaymentDetails";
const String baseUrlAppEngineFunctions =
    "https://development-dot-top-design-395510.ue.r.appspot.com"; // deployment baseURl = https://top-design-395510.ue.r.appspot.com
