// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8inIzoO71nuPDfH0ZED__OppLmbBkiYw',
    appId: '1:25989559034:web:00bcd96fde3b747f64cf43',
    messagingSenderId: '25989559034',
    projectId: 'blukers-development',
    authDomain: 'blukers-development.firebaseapp.com',
    databaseURL: 'https://blukers-development-default-rtdb.firebaseio.com',
    storageBucket: 'blukers-development.appspot.com',
    measurementId: 'G-6RRZVJSLKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnBA1yI928GjU892Q0_z3IrisrPB00CM',
    appId: '1:25989559034:android:9d0ff9f7910a037664cf43',
    messagingSenderId: '25989559034',
    projectId: 'blukers-development',
    databaseURL: 'https://blukers-development-default-rtdb.firebaseio.com',
    storageBucket: 'blukers-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDCHe61XTkxnjePSE6U6vJvHB3exzjHpk',
    appId: '1:25989559034:ios:d028a7a2865bae0964cf43',
    messagingSenderId: '25989559034',
    projectId: 'blukers-development',
    databaseURL: 'https://blukers-development-default-rtdb.firebaseio.com',
    storageBucket: 'blukers-development.appspot.com',
    androidClientId: '25989559034-8ld1mjucq0kti3ut5fcn9i6d28hqcolu.apps.googleusercontent.com',
    iosClientId: '25989559034-32qt09e8cg860hqv86805fomh6n5cfq1.apps.googleusercontent.com',
    iosBundleId: 'talk2victormarius.blukersUITests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDCHe61XTkxnjePSE6U6vJvHB3exzjHpk',
    appId: '1:25989559034:ios:64a2b3282bec97b564cf43',
    messagingSenderId: '25989559034',
    projectId: 'blukers-development',
    databaseURL: 'https://blukers-development-default-rtdb.firebaseio.com',
    storageBucket: 'blukers-development.appspot.com',
    androidClientId: '25989559034-8ld1mjucq0kti3ut5fcn9i6d28hqcolu.apps.googleusercontent.com',
    iosClientId: '25989559034-mfrt0s7jjm06v82m7ltjgo6j1v9illbh.apps.googleusercontent.com',
    iosBundleId: 'com.terralabor.blukers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8inIzoO71nuPDfH0ZED__OppLmbBkiYw',
    appId: '1:25989559034:web:21e3c0c831ed20ee64cf43',
    messagingSenderId: '25989559034',
    projectId: 'blukers-development',
    authDomain: 'blukers-development.firebaseapp.com',
    databaseURL: 'https://blukers-development-default-rtdb.firebaseio.com',
    storageBucket: 'blukers-development.appspot.com',
    measurementId: 'G-8RDP0NVN61',
  );

}