const List<String> SkillsEnglish = [
  'Welding',
  'Carpentry',
  'Plumbing',
  'Electrician',
  'Masonry',
  'Automotive Mechanics',
  'HVAC Installation and Repair',
  'Painting',
  'Landscaping',
  'Roofing',
  'Tile Setting',
  'Heavy Equipment Operation',
  'Concrete Finishing',
  'Drywall Installation',
  'Sheet Metal Work',
  'Glass Installation',
  'Locksmithing',
  'Ironworking',
  'Upholstery',
  'Machine Operation',
  'Metal Fabrication',
  'Plumbing Repair',
  'Cabinet Making',
  'Pipefitting',
  'Automotive Body Repair',
  'Refrigeration Repair',
  'Bricklaying',
  'Soldering',
  'Timber Framing',
  'Flooring Installation',
  'Masonry Restoration',
  'Diesel Mechanics',
  'Boilermaking',
  'Fence Installation',
  'Excavation',
  'Auto Painting',
  'Hydraulic Repair',
  'Asphalt Paving',
  'HVAC Maintenance',
  'Glass Blowing',
  'Rigging',
  'Tire Repair',
  'Weld Inspection',
  'Furniture Restoration',
  'Plastering',
  'Locksmithing',
  'Drain Cleaning',
  'Concrete Cutting',
  'Pipe Welding',
  'Metal Roofing',
  'Greenhouse Construction',
  'Air Duct Cleaning',
  'Cabinetry Installation',
  'Sewer Line Repair',
  'Roofing Repair',
  'Industrial Sewing',
  'Boat Repair',
  'Auto Detailing',
  'Stone Cutting',
  'Blacksmithing',
  'Scaffolding Assembly',
  'Drywall Taping',
  'Industrial Painting',
  'Elevator Maintenance',
  'Surveying',
  'Gutter Installation',
  'Steamfitting',
  'Masonry Cleaning',
  'Fence Repair',
  'Carpentry Finishing',
  'Irrigation System Installation',
  'Sign Making',
  'Plaster Repair',
  'Sheet Metal Roofing',
  'Rigging Inspection',
  'Glass Repair',
  'Auto Upholstery',
  'Foundry Work',
  'Bicycle Repair',
  'Lawnmower Repair',
  'Metal Casting',
  'Pipe Laying',
  'Hydraulic System Repair',
  'Metalworking',
  'Woodworking',
  'Boat Building',
  'Drainage System Installation',
  'Masonry Waterproofing',
  'Concrete Formwork',
  'Brick Cutting',
  'Asphalt Sealcoating',
  'Automotive Welding',
  'Rigging Supervision',
  'Glass Cutting',
  'Lock Installation',
  'Irrigation System Maintenance',
  'Stone Carving',
  'Carpentry Framing',
  'Welding Inspection',
  'Steamfitting Maintenance',
  'Foundry Casting',
  'Bicycle Assembly'
];

const List<String> SkillsSpanish = [
  'Soldadura',
  'Carpintería',
  'Fontanería',
  'Electricista',
  'Albañilería',
  'Mecánica Automotriz',
  'Instalación y Reparación de HVAC',
  'Pintura',
  'Paisajismo',
  'Techado',
  'Colocación de Azulejos',
  'Operación de Maquinaria Pesada',
  'Acabado de Hormigón',
  'Instalación de Paneles de Yeso',
  'Trabajo de Chapa',
  'Instalación de Vidrios',
  'Cerrajería',
  'Trabajo de Hierro',
  'Tapicería',
  'Operación de Máquinas',
  'Fabricación de Metales',
  'Reparación de Fontanería',
  'Fabricación de Gabinetes',
  'Instalación de Tuberías',
  'Reparación de Carrocería Automotriz',
  'Reparación de Refrigeración',
  'Colocación de Ladrillos',
  'Soldadura Blanda',
  'Estructura de Madera',
  'Instalación de Suelos',
  'Restauración de Albañilería',
  'Mecánica Diesel',
  'Fabricación de Calderas',
  'Instalación de Vallas',
  'Excavación',
  'Pintura de Autos',
  'Reparación Hidráulica',
  'Pavimentación de Asfalto',
  'Mantenimiento de HVAC',
  'Soplado de Vidrio',
  'Aparejos',
  'Reparación de Neumáticos',
  'Inspección de Soldadura',
  'Restauración de Muebles',
  'Enlucido',
  'Cerrajería',
  'Limpieza de Desagües',
  'Corte de Hormigón',
  'Soldadura de Tuberías',
  'Techado de Metal',
  'Construcción de Invernaderos',
  'Limpieza de Conductos de Aire',
  'Instalación de Gabinetes',
  'Reparación de Líneas de Alcantarillado',
  'Reparación de Techos',
  'Costura Industrial',
  'Reparación de Barcos',
  'Detallado de Autos',
  'Corte de Piedra',
  'Herrería',
  'Montaje de Andamios',
  'Cintado de Paneles de Yeso',
  'Pintura Industrial',
  'Mantenimiento de Ascensores',
  'Topografía',
  'Instalación de Canalones',
  'Instalación de Tuberías de Vapor',
  'Limpieza de Albañilería',
  'Reparación de Vallas',
  'Acabado de Carpintería',
  'Instalación de Sistemas de Riego',
  'Fabricación de Señales',
  'Reparación de Yeso',
  'Techado de Chapa Metálica',
  'Inspección de Aparejos',
  'Reparación de Vidrios',
  'Tapicería de Autos',
  'Trabajo de Fundición',
  'Reparación de Bicicletas',
  'Reparación de Cortacéspedes',
  'Fundición de Metales',
  'Tendido de Tuberías',
  'Reparación de Sistemas Hidráulicos',
  'Trabajo de Metales',
  'Carpintería',
  'Construcción de Barcos',
  'Instalación de Sistemas de Drenaje',
  'Impermeabilización de Albañilería',
  'Encofrado de Hormigón',
  'Corte de Ladrillos',
  'Sellado de Asfalto',
  'Soldadura Automotriz',
  'Supervisión de Aparejos',
  'Corte de Vidrio',
  'Instalación de Cerraduras',
  'Mantenimiento de Sistemas de Riego',
  'Tallado de Piedra',
  'Enmarcado de Carpintería',
  'Inspección de Soldadura',
  'Mantenimiento de Tuberías de Vapor',
  'Fundición de Metal',
  'Montaje de Bicicletas'
];
